# Generated by Django 3.1.5 on 2021-02-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yabouapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('postdate', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('war', '軍事'), ('life', '内政'), ('other', 'その他')], max_length=50)),
            ],
        ),
    ]
